[package]
name = "weovim"
version = "0.1.0"
authors = ["Luis Holanda <luiscmholanda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = { git = "https://github.com/daa84/neovim-lib" }
crossbeam-channel = "0.3.9"
mimalloc = "0.1.6"
